Repository Stratio/kind, pull requests merged in 2023-10, with the labels that each got.

#320 [CLOUD-109] Integrar GKE como nuevo provider
  go.mod
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: ok-to-test, skip doUT, 0.4.0

#298 Improve execute command retries
  pkg/commons/utils.go
Labels: ok-to-test, 0.4.0

#334 Prepare version 0.3.3
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/version/version.go
Labels: ok-to-merge, skip doUT, 0.3.3

#333 Add remote command execution retries
  pkg/commons/utils.go
Labels: ok-to-test, skip doUT, 0.3.3

#335 Feature/add infra validations
  CHANGELOG.md
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
  pkg/cluster/internal/validate/validate.go
  pkg/cmd/kind/version/version.go
Labels: dont merge, ok-to-test, skip doUT, 0.4.0

#336 fix: fix eksvalidator AZs
  README.md
  pkg/build/nodeimage/buildcontext.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: bug, ok-to-test, hotfix, 0.2.1

#340 Prepare new release
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/version/version.go
Labels: ok-to-merge, skip doUT, 0.3.3

#342 Add stratio-docs Stratio/document
  CODEOWNERS
Labels: ok-to-test

#337 chore: validate region exists
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/gcp.go
Labels: ok-to-test, 0.4.0

#345 Fix stratio_docs release 0.2
  stratio-docs/en/modules/ROOT/assets/images/amis.png
  stratio-docs/en/modules/ROOT/assets/images/build-ami-ubuntu-2204-part1.png
  stratio-docs/en/modules/ROOT/assets/images/build-ami-ubuntu-2204-part2.png
  stratio-docs/en/modules/ROOT/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/en/modules/ROOT/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/en/modules/ROOT/assets/images/deps-gce.png
  stratio-docs/en/modules/ROOT/assets/images/desp-ami.png
  stratio-docs/en/modules/ROOT/assets/images/google-service-account.png
  stratio-docs/en/modules/ROOT/assets/images/internet-gatway.png
  stratio-docs/en/modules/ROOT/assets/images/segurity-group.png
  stratio-docs/en/modules/ROOT/assets/images/vpc-id.png
  stratio-docs/es/modules/ROOT/assets/images/amis.png
  stratio-docs/es/modules/ROOT/assets/images/build-ami-ubuntu-2204-part1.png
  stratio-docs/es/modules/ROOT/assets/images/build-ami-ubuntu-2204-part2.png
  stratio-docs/es/modules/ROOT/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/es/modules/ROOT/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/es/modules/ROOT/assets/images/deps-azure.png
  stratio-docs/es/modules/ROOT/assets/images/deps-gce.png
  stratio-docs/es/modules/ROOT/assets/images/desp-ami.png
  stratio-docs/es/modules/ROOT/assets/images/google-service-account.png
  stratio-docs/es/modules/ROOT/assets/images/internet-gatway.png
  stratio-docs/es/modules/ROOT/assets/images/segurity-group.png
  stratio-docs/es/modules/ROOT/assets/images/vpc-id.png
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/aws-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp-image-builder.adoc
Labels: documentation, ok-to-merge, 0.2.0

#341 [CLOUD-114] Setear PriorityClass system-node-critical para el DaemonSet capz-nmi
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, hotfix, 0.3.3

#347 Remove println
  pkg/cluster/internal/validate/azure.go
Labels: bug, ok-to-merge, skip doUT, 0.4.0

#348 Fix k8s version common validation for gke
  pkg/cluster/internal/validate/common.go
Labels: bug, ok-to-merge, skip doUT, 0.4.0

#339 [CLOUD-108] Actualizar provider de Azure a 1.11.x
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.4.0

#346 Fix Images Documentation release 0.3
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/en/modules/ROOT/assets/images/amis.png
  stratio-docs/en/modules/ROOT/assets/images/build-ami-ubuntu-2204-part1.png
  stratio-docs/en/modules/ROOT/assets/images/build-ami-ubuntu-2204-part2.png
  stratio-docs/en/modules/ROOT/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/en/modules/ROOT/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/en/modules/ROOT/assets/images/deps-gce.png
  stratio-docs/en/modules/ROOT/assets/images/desp-ami.png
  stratio-docs/en/modules/ROOT/assets/images/google-service-account.png
  stratio-docs/en/modules/ROOT/assets/images/internet-gatway.png
  stratio-docs/en/modules/ROOT/assets/images/segurity-group.png
  stratio-docs/en/modules/ROOT/assets/images/vpc-id.png
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/es/modules/ROOT/assets/images/amis.png
  stratio-docs/es/modules/ROOT/assets/images/build-ami-ubuntu-2204-part1.png
  stratio-docs/es/modules/ROOT/assets/images/build-ami-ubuntu-2204-part2.png
  stratio-docs/es/modules/ROOT/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/es/modules/ROOT/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/es/modules/ROOT/assets/images/deps-gce.png
  stratio-docs/es/modules/ROOT/assets/images/desp-ami.png
  stratio-docs/es/modules/ROOT/assets/images/google-service-account.png
  stratio-docs/es/modules/ROOT/assets/images/internet-gatway.png
  stratio-docs/es/modules/ROOT/assets/images/segurity-group.png
  stratio-docs/es/modules/ROOT/assets/images/vpc-id.png
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/aws-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/aws_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, 0.3.0

#351 fix: Fix helm repo authorization
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, hotfix, 0.3.3

#352 chore: azure provider to 1.11.4
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: bug, ok-to-test, 0.4.0

#350 fix: Fix helm repo authorization
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: bug, ok-to-test, hotfix, backport, 0.4.0

#353 Fix/azure aks az validation
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-test, skip doUT

#317 FLOW-2863 Testing in CICD Jenkins
  Dockerfile
  Jenkinsfile
  Makefile
  bin/deploy.sh
Labels: dont merge, WIP, testing-eks, AT-eks-smoke
