Repository Stratio/kind, pull requests merged in 2023-08, with the labels that each got.

#218 [CLOUD-63] Desacoplar funciones del provider
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/aws.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.3.0

#225 Add Azure file CSI driver
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0

#228 Fix templates quotes
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/gcp.tmpl
Labels: ok-to-test, 0.3.0

#224 [CLOUD-36] [GCP] Crear GNP para el IMDS
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/allow-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/deny-all-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/gcp-compute-persistent-disk-csi-driver.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.0

#217 [CLOUD-31] Add Azure Perm doc
  docs/azure/Image Builder/Permissions/Errros.md
  docs/azure/Image Builder/Permissions/azure_permission_ref.md
  docs/azure/Image Builder/Permissions/capz-role-control-plane.json
  docs/azure/Image Builder/Permissions/capz-role-node.json
  docs/azure/Image Builder/Permissions/capz-role-restricted.json
Labels: ok-to-merge, 0.3.0

#223 Integrate cluster operator
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/commons/cluster.go
Labels: ok-to-merge, 0.3.0

#229 Fix keoscluster deployment
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-merge, 0.3.0

#230 Fix external volume filesystem
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.tmpl
Labels: ok-to-merge, 0.3.0

#226 Add Azure file CSI driver
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#231 Fix forwarders check
  pkg/commons/cluster.go
Labels: ok-to-test

#227 [CLOUD-67] Asegurar integracion con keos-installer 1.x
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/validate/secrets.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.3.0

#148 [EOS-11510] Refinar Permisos AWS Unmanaged
  docs/aws/Permissions/Errros.md
  docs/aws/Permissions/aws_permission_ref.json
  docs/aws/Permissions/aws_permission_ref.md
Labels: documentation, ok-to-merge, 0.3.0

#215 Separate control plane identity
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.tmpl
  pkg/commons/cluster.go
Labels: ok-to-test, 0.3.0

#232 [CLOUD-74] Desplegar cluster-operator desde repo Helm
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test

#233 [CLOUD-76] Agregar parametro de --validate-only
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: ok-to-test, 0.3.0

#234 fix error message adding helm repo
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.0

#235 Clean code
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#236 Sync validations with cluster-operator
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
Labels: ok-to-merge, 0.3.0

#237 Fix validations
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-merge, 0.3.0

#238 Fix aks node validations
  pkg/cluster/internal/validate/azure.go
Labels: bug, 0.3.0

#239 Fix when only one az is passed
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
Labels: bug, ok-to-test, 0.3.0

#242 Fix Azure AKS identity
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.aks.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/commons/cluster.go
Labels: bug, ok-to-merge, 0.3.0

#243 Remove az validation
  pkg/commons/cluster.go
Labels: bug, ok-to-merge, 0.3.0

#244 Clean keoscluster data
  pkg/commons/cluster.go
Labels: ok-to-merge, 0.3.0

#245 chore: delete unneeded field
  pkg/commons/cluster.go
Labels: ok-to-merge, 0.3.0

#246 Scale keoscluster to 2 instances in workload cluster
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.0

#247 Add keoscluster milestone
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#250 [Cloud-83] Actualizar la version del provisioner
  pkg/cmd/kind/version/version.go
Labels: ok-to-test, 0.3.0

#248 Fix keoscluster scale to 1 in local cluster
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#252 Upgrade logging permission aws/0.3.0
  docs/aws/Permissions/Errros.md
  docs/aws/Permissions/aws_permission_ref.json
  docs/aws/Permissions/aws_permission_ref.md
Labels: ok-to-test, 0.3.0, skip doUT

#251 Upgrade azure provider for unmanaged
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0

#249 Deploy cluster operator before
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-test, 0.3.0

#253 [CLOUD-44] Actualizar versiones de CAPx, calico y cert-manager
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0
