Repository Stratio/kind, pull requests merged in 2023-06, with the labels that each got.

#131 [EOS-11410] Soportar ACR como docker registry para Azure
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#113 [EOS-11312] [Azure] Soportar control-plane no gestionado (en VMs)
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/calico-helm-values.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cmd/kind/create/cluster/validation/azurevalidator.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#134 [EOS-1144][GCP] Usar additionalNetworkTags para quitar dependencia de cluster_name en grupo de nodos
  pkg/cluster/internal/create/actions/createworker/templates/gcp.tmpl
Labels: ok-to-test, 0.2.0

#138 [EOS-11311] Refinar Permisos
  docs/aws/Image  Builder/aws_image_builder.adoc
  docs/aws/Permissions/Cloud_Formation.json
  docs/aws/Permissions/Errros.md
  docs/aws/Permissions/aws_permission_ref.json
  docs/aws/Permissions/aws_permission_ref.md
Labels: ok-to-test

#126 Update cluster-api to 1.4.3
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#141 Fix eks calico installation
  pkg/cluster/internal/create/actions/createworker/templates/calico-helm-values.tmpl
Labels: bug, ok-to-test, 0.2.0

#139 [EOS-11474] [EKS] A01:2021 - Broken Access Control - IMDS sensitive credentials exposure
  pkg/cluster/internal/create/actions/createworker/files/allow-capa-egress-imds_gnetpol.yaml
Labels: ok-to-test, 0.2.0

#143 [EOS-11345][EKS] El CIDR secundario para Pods falla con infra custom según el órden de las subnets
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#135 Improve wait for control planes condition
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-test, 0.2.0

#121 [EOS-11300] Get azs of defined subnets in descriptor
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
  pkg/cmd/kind/create/cluster/validation/validator.go
Labels: ok-to-test, 0.2.0

#151 Improve dockerfile
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#84 Added taints to worker nodes
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp.tmpl
  pkg/cmd/kind/create/cluster/validation/commonvalidations.go
  pkg/commons/cluster.go
Labels: ok-to-merge, 0.2.0

#150 [EOS-11509] Upgrade cluster-api-provider-aws to upstream's
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#146 Bump gcp provider
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: ok-to-test, 0.2.0

#124 [EOS-11342] Exponer métricas de calico-node y calico-typha
  pkg/cluster/internal/create/actions/createworker/files/calico-metrics.yaml
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.2.0

#156 Bump gcp csi driver && rollback template to file
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/files/gcp-compute-persistent-disk-csi-driver.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: ok-to-merge, 0.2.0

#149 [EOS-11375] Bump cluster-autoscaler version to 1.27.x
  DEPENDENCIES
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#157 fix: fix env CAPG dockerfile
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, hotfix, 0.2.0

#152 [EOS-11480] Cancelar instalacion si error en clusterawsadm ([CAPA] Ensuring IAM security)
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.2.0

#158 Bump eks addons
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
Labels: ok-to-test, 0.2.0

#169 Bump azure provider
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.2.0

#162 [EOS-11523] [Azure/AKS] Add taints
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
Labels: ok-to-test, 0.2.0

#167 Fix azure csi driver namespace
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: bug, ok-to-test, 0.2.0

#165 [EOS-11524] [Azure] Allow custom images
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
Labels: ok-to-test, 0.2.0

#163 [EOS-11525] [AKS] Allow spot instances
  pkg/cluster/internal/create/actions/createworker/templates/azure.aks.tmpl
Labels: ok-to-test, 0.2.0

#168 [EOS-11436] Configurar EFS en el descriptor (para renderizar el keos.yaml)
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#172 Rollback eks vpc-cni addon
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
Labels: ok-to-test, hotfix, 0.2.0

#174 [EOS-11529] Support infra custom
  pkg/cluster/internal/create/actions/createworker/templates/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#173 [EOS-11435] Add suppor for internal ingress service
  Jenkinsfile
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/all/allow-all-egress_netpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-capa-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/aws/deny-all-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/aws/internal-ingress-nginx.yaml
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/files/azure/internal-ingress-nginx.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/internal-ingress-nginx.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/rbac-loadbalancing.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.2.0

#170 Feature/eos 11486 storageclass
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-capa-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/create/cluster/validation/azurevalidator.go
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
  pkg/cmd/kind/create/cluster/validation/gcpvalidator.go
  pkg/cmd/kind/create/cluster/validation/validationutils.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#176 fixed bug
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
Labels: dont merge, ok-to-test

#178 Fix/aks bug in sc
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-merge

#180 fixing bugs in GCP when SC is not declarated
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: bug, ok-to-test

#182 changed to standard sc by default
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: bug, ok-to-merge

#183 fixed iops requirements
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
Labels: bug, ok-to-merge, hotfix

#181 chore: improve resiliency filtering aws subnets
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
Labels: bug, ok-to-merge, hotfix

#185 Adding pv override vars
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-test, 0.2.0

#186 added extra volume name validation in azure
  pkg/cmd/kind/create/cluster/validation/azurevalidator.go
Labels: bug, ok-to-test, 0.2.0
