Repository Stratio/kind, pull requests merged in 2023-07, with the labels that each got.

#193 Prepare next version
  CHANGELOG.md
  VERSION
Labels: 0.3.0

#192 Bring latest changes in 0.2 to 0.3
  pkg/build/nodeimage/const_storage.go
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: 0.3.0

#194 Add GCP perm doc
  docs/gcp/Image  Builder/gcp_image_builder.adoc
  docs/gcp/Permissions/gcp_permissions_ref.md
Labels: 0.2.0

#195 Add GCP perm doc
  docs/gcp/Image  Builder/gcp_image_builder.adoc
  docs/gcp/Permissions/gcp_permission_ref.md
Labels: 0.3.0

#196 Revert version
  VERSION
Labels: 0.2.0

#191 changed clusterId to clusterName and descriptorfile to keoscluster
  docs/gcp/Permissions/gcp_permissions_ref.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp.tmpl
  pkg/cmd/kind/create/cluster/validation/azurevalidator.go
  pkg/cmd/kind/create/cluster/validation/commonvalidations.go
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
  pkg/cmd/kind/create/cluster/validation/gcpvalidator.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: dont merge, ok-to-test, 0.3.0

#198 Fix wait conditions
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-test, 0.3.0

#199 Fix wait conditions
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-test, 0.2.0

#171 Add eks secrets encryption
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/commons/cluster.go
Labels: ok-to-test, 0.3.0

#197 [CLOUD-34] [EKS] Agregar condiciones a la GNP del IMDS
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-capa-egress-imds_gnetpol.yaml
Labels: ok-to-test, 0.3.0

#98 [EOS-11196] Support AWS unmanaged
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cmd/kind/create/cluster/validation/awsvalidator.go
  pkg/cmd/kind/create/cluster/validation/validator.go
Labels: ok-to-test, 0.3.0

#203 Refactor storageclass
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.3.0

#205 Backport storage class refactor fixes
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/azure/azure-storage-classes.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cmd/kind/create/cluster/validation/gcpvalidator.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
Labels: bug, ok-to-merge, 0.2.1

#208 add EN folder to stratio-docs
  stratio-docs/en/antora.yml
  stratio-docs/en/modules/ROOT/assets/attachments/example-eks-md.yaml
  stratio-docs/en/modules/ROOT/assets/attachments/example-gcp-md.yaml
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/en/modules/ROOT/assets/images/autoescalado.png
  stratio-docs/en/modules/ROOT/assets/images/controllers.png
  stratio-docs/en/modules/ROOT/assets/images/crds.png
  stratio-docs/en/modules/ROOT/assets/images/eks-reference-architecture.png
  stratio-docs/en/modules/ROOT/assets/images/escalado-manual.png
  stratio-docs/en/modules/ROOT/assets/images/self-healing.png
  stratio-docs/en/modules/ROOT/assets/images/upgrade-cp.png
  stratio-docs/en/modules/ROOT/assets/images/upgrade-w.png
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/introduction.adoc
  stratio-docs/en/modules/ROOT/pages/operations.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, WIP

#202 added 1 replica to cluster-autoscaler
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-merge, 0.3.0

#204 Bump cluster-api-provider-aws
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0

#213 [CLOUD-47] Actualizar CAPG (a 1.4.0)
  CHANGELOG.md
  DEPENDENCIES
  README.md
  pkg/build/nodeimage/buildcontext.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cmd/kind/version/version.go
  site/config.toml
Labels: ok-to-test, 0.3.0

#212 [CLOUD-22] Configurar DNSs forwarders custom en coredns
  CHANGELOG.md
  docs/cloud-provisioner/Versiones.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/common/allow-all-egress_netpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/common/calico-metrics.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/coredns_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/coredns_configmap-aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/coredns_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/coredns_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/gcp.tmpl
  pkg/commons/cluster.go
Labels: ok-to-test, 0.3.0

#153 [GCP] Set bind-address to 0.0.0.0 to be able to scrape metrics from kubernetes controller-manager, scheduler and kube-proxy
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/gcp.tmpl
Labels: ok-to-test, 0.3.0

#211 Bump cluster-api-provider-azure
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0

#214 [CLOUD-32] Revisar fase de validaciones
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
  pkg/cluster/internal/validate/secrets.go
  pkg/cluster/internal/validate/utils.go
  pkg/cluster/internal/validate/validate.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/create/cluster/validation/awsvalidator.go
  pkg/cmd/kind/create/cluster/validation/azurevalidator.go
  pkg/cmd/kind/create/cluster/validation/commonvalidations.go
  pkg/cmd/kind/create/cluster/validation/gcpvalidator.go
  pkg/cmd/kind/create/cluster/validation/validationutils.go
  pkg/cmd/kind/create/cluster/validation/validator.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.3.0

#219 Validate at least there is one worker without spot and taints
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
Labels: ok-to-test, 0.3.0

#221 Bump ci memory requests
  Jenkinsfile
Labels: ok-to-merge, 0.3.0

#220 Fix azure network validations
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-merge, 0.3.0
