Repository Stratio/kind, pull requests merged in 2023-12, with the labels that each got.

#383 Added annotations
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/common/coredns_pdb.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/gcp-compute-persistent-disk-csi-driver.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl
Labels: ok-to-merge, skip doUT

#385 [branch-0.3] Nav links fixed
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation

#386 [branch-0.3] Dead links fixed
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation

#389 [CLOUD-158] Actualizar scripts de upgrade para 0.3.5
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-test, skip doUT, 0.3.5

#391 Update introduction.adoc
  stratio-docs/en/modules/ROOT/pages/introduction.adoc
  stratio-docs/es/modules/ROOT/pages/introduction.adoc
Labels: skip doUT

#396 Update doc create role for eks deployments
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: 0.3.0

#399 Fix docs for 0.3
  docs/aws/Permissions/aws_permission_ref.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: skip doUT

#403 Refinar y documentar Setup de nuevas cuentas
  docs/aws/accounts/new_accounts.md
Labels: 0.4.0

#404 Fix storage class labels validation
  pkg/cluster/internal/validate/common.go
Labels: ok-to-test, skip doUT, 0.3.6

#405 Prepare release 0.3.6
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/version/version.go
  scripts/upgrade-provisioner_v0.3.py
Labels: skip doUT
