Repository Stratio/kind, pull requests merged in 2023-03, with the labels that each got.

#52 [EOS-11007] No ejecutar el paso de "IAM security" si se indica --avoid-creation
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-test

#53 Align image versions
  pkg/apis/config/defaults/image.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge

#46 [EOS-10979] Refactor/eos 10979 refactoring credentials
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/utils.go
Labels: ok-to-test

#48 [EOS-10983] Make `external-dns` optional
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: ok-to-test

#58 Fix gcp registry url
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#57 Fix autoscaler conditions
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#63 [EOS-11006] No funciona el parametro zone_distribution
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#54 [EOS-11009] Add labels to node groups
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#68 Fix default root volume size in eks template
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
Labels: ok-to-test

#40 [EOS-10868] Integrated VPC custom
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-test

#65 [EOS-11000] Especificación de discos para mountpoints
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#71 Add private ecr registry support
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/utils.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test

#66 [EOS-10982] [GCP] Feature/eos 10982 gcp vpc custom
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
Labels: ok-to-test

#69 Autoscaler helm chart offline installation
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/utils.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test

#75 [EOS-1931] Formato de k8s en el cluster descriptor
  pkg/cluster/internal/create/actions/cluster/cluster.go
Labels: ok-to-test

#76 [EOS-11097] Getting AZs in region
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: dont merge, ok-to-test

#79 Minor Fixes
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: ok-to-test

#81 fix/node_image required condition
  pkg/cluster/internal/create/actions/cluster/cluster.go
Labels: ok-to-merge, hotfix

#83 Add retries retrieving kubeconfig
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-test
