Repository Stratio/kind, pull requests merged in 2023-05, with the labels that each got.

#97 [EOS-11181] Documentar creacion de imagenes para GCP y EKS
  docs/aws/aws_image_builder.adoc
  docs/gcp/gcp_image_builder.adoc
  scripts/README.md
  scripts/aws_vpc.py
Labels: documentation, ok-to-test

#99 [EOS-10815] [EKS] Allow access to Docker registries
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
Labels: ok-to-test

#104 Disable clusterctl version check
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test

#108 Bump tigera-operator version
  pkg/cluster/internal/create/actions/createworker/templates/calico-helm-values.tmpl
Labels: ok-to-test

#103 [EOS-11148] Refinar el uso de un CIDR (secundario) específico para Pods
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cmd/kind/create/cluster/validation/eksvalidator.go
  pkg/commons/cluster.go
Labels: enhancement, ok-to-test, 0.2.0

#106 chore(backport): Get available AZ in region
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.1.1

#116 [EOS-11399] Remove optional internal domain
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/commons/cluster.go
Labels: backport

#107 [EOS-11310] [EKS] Cambiar despliegue de coredns como addon
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
Labels: ok-to-test, 0.2.0

#109 [EKS] Cambiar despliegue de kube-proxy como addon
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
Labels: ok-to-test, 0.2.0

#117 [EOS-11358] tigera-operator no llega al APIserver
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-test, 0.2.0

#120 [EOS-11353] Imprimir version Stratio y no de kind
  pkg/cmd/kind/root.go
  pkg/cmd/kind/version/version.go
Labels: ok-to-test, 0.2.0

#118 [EOS-11269] [validaciones] error al indicar un grupo con az, zone_distribution=balanced y quantity<3
  pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp.tmpl
  pkg/cmd/kind/create/cluster/validation/commonvalidations.go
  pkg/commons/cluster.go
Labels: bug, ok-to-test, 0.2.0

#112 [EOS-11379] Soportar Kubernetes v1.25
  pkg/cluster/internal/create/actions/createworker/calico.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/gcp-compute-persistent-disk-csi-driver.tmpl
Labels: ok-to-test, 0.2.0

#122 Fix node groups
  pkg/cmd/kind/create/cluster/validation/commonvalidations.go
  pkg/commons/cluster.go
Labels: ok-to-test, 0.2.0

#119 [EOS-11411] [ClusterAPI] Fix behaviour of keos flavour parameter
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: bug, ok-to-test, 0.1.1

#111 fix: backport fix deploy_tigera_operator
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: bug, ok-to-test, 0.1.1

#125 fix: set fixed value of
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: bug, ok-to-test, 0.1.1

#130 Fix Azure keos integration
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.2.0
