Repository Stratio/kind, pull requests merged in 2023-09, with the labels that each got.

#257 Fix typo in azure validation
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-merge, 0.3.0

#255 Install cloud-provider-azure in kube-system namespace
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: bug, ok-to-test, 0.3.0

#256 aws cloud provider external
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, 0.3.0

#258 Update azure provider and its csi drivers
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0

#260 Update image builder doc
  docs/aws/Image  Builder/aws_image_builder.adoc
  docs/azure/Image Builder/azure_image_builder.adoc
  docs/gcp/Image  Builder/gcp_image_builder.adoc
Labels: documentation, ok-to-test, 0.3.0

#262 Rollback cluster-api version
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: bug, ok-to-test, 0.3.0

#263 Fix/add new selector to aws global network policy
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-egress-imds_gnetpol.yaml
Labels: bug, ok-to-test, 0.3.0, skip doUT

#207 Release 0.2 documentation
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/example-aks-md.yaml
  stratio-docs/es/modules/ROOT/assets/attachments/example-eks-md.yaml
  stratio-docs/es/modules/ROOT/assets/attachments/example-gcp-md.yaml
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-temp-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-nodes-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-role.json
  stratio-docs/es/modules/ROOT/assets/images/arq-intro.png
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/aws_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/introduction.adoc
  stratio-docs/es/modules/ROOT/pages/operations.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, ok-to-test, 0.2.0

#264 change reference to capi version
  CHANGELOG.md
  DEPENDENCIES
Labels: ok-to-merge, 0.3.0

#265 Increase calico namespace timeout
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.0

#269 bump capx versions
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, 0.3.0

#273 Bump to M4
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#274 Increase mh and clean code
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.0

#272 [CLOUD-94] Validaciones: si hay parameters, no tener en cuenta encryptionKey ni class en spec.storageclass
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/gcp.go
Labels: ok-to-test, 0.3.0

#270 Move management to worker cluster
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0, skip doUT

#275 Added rollout status to wait for keoscluster controller ready
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0, skip doUT

#279 Fix add override vars
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: bug, ok-to-test, 0.3.0

#278 fix: exit with error when subnet doesn't exist
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: bug, ok-to-test, 0.3.0

#277 Change unbalance validation
  pkg/cluster/internal/validate/common.go
Labels: bug, ok-to-merge, 0.3.0

#280 Clean highly available
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
Labels: bug, ok-to-test, 0.3.0

#283 Clean spot
  pkg/commons/cluster.go
Labels: bug, ok-to-test, 0.3.0

#287 Fix clusterctl version
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.0, skip doUT

#286 Add some retries
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: dont merge, WIP, ok-to-test, 0.3.0

#288 Bump cluster-operator to 0.1.0-f95b77e
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0, skip doUT

#289 chore: handle acr token error
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: ok-to-test, 0.3.0

#292 Fix highly available false
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
Labels: bug, ok-to-test, 0.3.0

#291 Fix dependencies
  DEPENDENCIES
Labels: ok-to-test, 0.3.0, skip doUT

#293 Update versiones.md
  docs/cloud-provisioner/Versiones.md
Labels: ok-to-test, 0.3.0, skip doUT

#271 Doc/image builder aws
  docs/aws/Image  Builder/aws_image_builder.adoc
Labels: documentation, 0.3.0

#297 Fix network validations
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: bug, ok-to-merge, 0.3.0

#299 Fix aws pods_cidr validation
  pkg/cluster/internal/validate/aws.go
Labels: ok-to-test, 0.3.0

#300 Bump cluster-operator to 0.1.0-7facf0b
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#304 Remove retries
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#305 Fix ecr login when ecr is in another region
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: bug, ok-to-test, 0.3.0

#307 Bump cluster op release
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.3.0

#302 [branch-0.17.0-0.2] 1st part reviewed
  CODEOWNERS
  Jenkinsfile
  stratio-docs/en/modules/ROOT/assets/attachments/example-aks-md.yaml
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-nodes-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/en/modules/ROOT/assets/images/arq-intro.png
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/aws-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/aws_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/azure_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp-image-builder.adoc
  stratio-docs/es/modules/ROOT/pages/gcp_image_builder.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, WIP, 0.2.1

#306 Fix workers name validation
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/common.go
Labels: bug, ok-to-test, 0.3.1

#309 Fix workes name validation
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/common.go
Labels: bug, ok-to-test, 0.4.0

#312 Update codeowners
  CODEOWNERS
Labels: ok-to-test, skip doUT, 0.3.1

#308 [CLOUD-52] Imprimir build de la version
  Makefile
  pkg/cmd/kind/version/version.go
Labels: ok-to-test, 0.3.1

#290 [CLOUD-86] Eliminar lógica en cloud-provisioner migrada al cluster-operator
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/aws.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.aks.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/azure.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/gcp.tmpl
  pkg/commons/cluster.go
Labels: ok-to-merge, skip doUT, 0.4.0

#315 Fix Pause version
  docs/cloud-provisioner/Versiones.md
Labels: ok-to-test, 0.3.0, skip doUT

#316 [CLOUD-80] Utilizar azure driver v1.10 para Azure unmanaged
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: bug, ok-to-test, 0.3.1

#318 Bump cluster-operator prerrelease
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.1.1, skip doUT

#323 Add iam permissions
  docs/aws/Permissions/Cloud_Formation.json
  docs/aws/Permissions/Errros.md
  docs/aws/Permissions/aws_permission_ref.md
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/en/modules/ROOT/pages/azure-image-builder.adoc
  stratio-docs/en/modules/ROOT/pages/gcp-image-builder.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-temp-policy.json
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-test, 0.2.0, skip doUT

#324 Bump to cluster-operator 0.1.1-0146b6e
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, skip doUT, 0.3.1
