Repository Stratio/kind, pull requests merged in 2023-02, with the labels that each got.

#26 Namespace per cluster
  DEPENDENCIES
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: dont merge

#27 [EOS-10845] Feature/eos 10847 cluster autoescaler integration
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/utils.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test

#36 [EOS-10927] Feature/eos 10927 create kind without apply manifest
  pkg/cluster/createoption.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/utils.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: ok-to-test

#41 [EOS-10953] fixed --retain bug
  pkg/cluster/createoption.go
Labels: ok-to-test

#37 [EOS-10849] Integrar GCP en cloud-provisioner
  DEPENDENCIES
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/eks.go
  pkg/cluster/internal/create/actions/createworker/files/calico-helm-values.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/utils.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge

#43 [EOS-10849] Integrar GCP en cloud-provisioner (Part II): Add gcp support to keos.yaml
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/create/keosinstaller/keosinstaller.go
Labels: ok-to-merge

#44 [EOS-10849] Integrar GCP en cloud-provisioner (Part III): Add gcp csi installation
  DEPENDENCIES
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/cluster/templates/gcp.tmpl
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/gcp-compute-persistent-disk-csi-driver.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/utils.go
Labels: ok-to-merge

#45 [EOS-10849] Fix gcp storageclass name
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: ok-to-merge

#38 [EOS-10929] Feature/eos 10929 upgrade credentials removing from descriptor
  pkg/cluster/internal/create/actions/cluster/cluster.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/utils.go
Labels: ok-to-merge
