Repository Stratio/kind, pull requests merged in 2023-11, with the labels that each got.

#361 Update branch 0.3 doc
  docs/aws/Permissions/Cloud_Formation.json
  docs/aws/Permissions/Errros.md
  docs/aws/Permissions/aws_permission_ref.json
  docs/aws/Permissions/aws_permission_ref.md
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
Labels: documentation, WIP, 0.3.4

#364 [Core] Add PDB and PriorityClass to capx components
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/aws/capa_pdb.yaml
  pkg/cluster/internal/create/actions/createworker/files/azure/capz_pdb.yaml
  pkg/cluster/internal/create/actions/createworker/files/gcp/capg_pdb.yaml
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/capi_pdb.tmpl
Labels: enhancement, ok-to-merge, 0.3.4

#366 [chore] prepare pre-release 0.3.4
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/version/version.go
Labels: 0.3.4

#360 Upgrade script to 0.3.0 from 0.2.0
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-test, skip doUT, 0.3.4

#368 Prepare new pre release
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-merge, skip doUT, 0.3.4

#369 New pre release
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-merge, skip doUT, 0.3.4

#372 Prepare release 0.3.4
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cmd/kind/version/version.go
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-merge, skip doUT, 0.3.4

#375 Add cluster-operator dependency
  DEPENDENCIES
Labels: ok-to-merge, skip doUT, 0.4.0

#381 Test cicd 4
  Jenkinsfile
Labels: dont merge, WIP, AT-eks-smoke

#370 [CLOUD-134] PriorityClass y PDBs para todos los controllers de clouds
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/capi_pdb.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/capx_pdb.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.4.0
