Repository Stratio/kind, pull requests merged in 2024-10, with the labels that each got.

#599 [PLT-817] Bump Tigera Operator version to v3.28.2
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-calico.txt
  bin/images/gcp/imagenes-csi-node.txt
  docs/cloud-provisioner/Versiones.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/templates/common/30/tigera-operator-helm-values.tmpl
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
Labels: ok-to-test, 0.6.0

#602 [PLT-806] GKE nodos privados
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/kubeadminit/init.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/commons/cluster.go
Labels: ok-to-test, 0.5.4

#603 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0.5.4

#605 [Fix] gcp pre-release version
  pkg/cluster/internal/create/actions/createworker/gcp.go
Labels: 0.5.4

#606 [PLT-917] Replace coredns yaml files with a single coredns tmpl file
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/gcp/coredns_rbac.yaml
  pkg/cluster/internal/create/actions/createworker/templates/gcp/coredns_deployment.tmpl
Labels: skip doUT, ok-to-review, 0.5.4

#607 [PLT-920] Added use-local-stratio-image flag to reuse local image
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
Labels: skip doUT, 0.5.4

#609 Update CHANGELOG.md
  CHANGELOG.md
Labels: ok-to-merge, skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.5.4

#611 [PLT-929] Removed calico installation as policy manager by helm chart in GKE
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/commons/cluster.go
Labels: ok-to-review, 0.5.4

#612 Fix CHANGELOG.md
  CHANGELOG.md
Labels: skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.5.4

#613 Added PLT-911 to changelog
  CHANGELOG.md
Labels: skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.5.4

#615 [PLT-923] Remove path /stratio from container image reference for kub…
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.5.4, need-cherry-pick-master

#617 [PLT-923] Remove path /stratio from container image reference for kub…
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, skip doUT, skip doGrypeScan, cherry-pick, 0.6.0, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks

#618 [PLT-923] Add path /kubebuilder for kube-rbac-proxy image url
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-review, 0.5.4, need-cherry-pick-master

#616 [PLT-915][PLT-891] Fixes to install with EKS
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/common/calico-metrics.yaml
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
Labels: bugfix, ok-to-review, 0.6.0

#620 [PLT-965] [GKE] Deshabilitar monitorización/logs gestionada
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/commons/cluster.go
Labels: ok-to-review, 0.5.4, need-cherry-pick-master

#623 Update capg-version dependencies
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, 0.5.4

#619 [PLT-988][PLT-992] Chore/plt 988 decoupling capg and dockerfile
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/providers/provider.go
  pkg/commons/cluster.go
Labels: feature, ok-to-review, 0.6.0

#625 Fix provider gcp image
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, 0.5.5
