Repository Stratio/kind, pull requests merged in 2024-03, with the labels that each got.

#502 [FIX] Remove print labels
  pkg/cluster/internal/validate/aws.go
Labels: bug, ok-to-merge, 0.5.0, cherry-pick

#504 Cherry pick execute command from 0.3
  pkg/commons/utils.go
Labels: bug, ok-to-merge, 0.5.0, cherry-pick

#495 [chore] Add offline image of aws load balancer controller manager
  bin/images/aws/imagenes-eks-distro.txt
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#497 Update - installatio.adoc - Add Aws unmanaged uncoupled perms
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#505 Update ami aws creation
  docs/aws/Image  Builder/aws_image_builder.adoc
  docs/azure/Image Builder/azure_image_builder.adoc
  docs/gcp/Image  Builder/gcp_image_builder.adoc
  stratio-docs/en/modules/operations-manual/pages/image-builder/aws-image-builder.adoc
  stratio-docs/es/modules/operations-manual/pages/image-builder/aws-image-builder.adoc
Labels: documentation, WIP, skip doUT, 0.4.0, skip doGrypeScan

#477 [CLOUD-201] Actualizar script de upgrade v0.4.0
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  scripts/upgrade-provisioner.py
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#507 [CLOUD-199] Add update-provisioner to Jenkins flow
  bin/package.sh
Labels: dont merge, skip doUT, 0.4.0, skip doGrypeScan

#506 Update ami aws creation
  docs/aws/Image  Builder/aws_image_builder.adoc
  docs/azure/Image Builder/azure_image_builder.adoc
  docs/gcp/Image  Builder/gcp_image_builder.adoc
  stratio-docs/en/modules/operations-manual/pages/image-builder/aws-image-builder.adoc
  stratio-docs/es/modules/operations-manual/pages/image-builder/aws-image-builder.adoc
Labels: documentation, WIP, skip doUT, skip doGrypeScan, 0.5.0

#509 Set priorityClass to cluster-api deployments in upgrade
  scripts/upgrade-provisioner.py
Labels: bug, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#508 Fix cluster-op version in upgrade script
  scripts/upgrade-provisioner.py
Labels: skip doUT, 0.4.0, skip doGrypeScan

#500 [CLOUD-213] Hacer opcional el despliegue del aws-loadbalancer-controller en el ClusterConfig (default: no instalar)
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-test, 0.5.0, cherry-pick

#496 [chore] Add offline image of aws load balancer controller manager
  bin/images/aws/imagenes-eks-distro.txt
Labels: ok-to-test, 0.5.0, cherry-pick

#514 Improve retrys & remove golang warnings
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/utils.go
  scripts/upgrade-provisioner.py
Labels: ok-to-test, 0.4.1

#519 Improve retrys & remove golang warnings
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/utils.go
Labels: bugfix, ok-to-merge, 0.5.0, cherry-pick

#518 Fix GHSA-xr7r-f8xq-vfvv
  CHANGELOG.md
  go.mod
  go.sum
Labels: bugfix, ok-to-merge, 0.5.0

#520 [CLOUD-222] Docs/cloud 222 offline images docs
  bin/images/aws/REGISTRY
  bin/images/aws/imagenes-aws.txt
  bin/images/aws/imagenes-capa.txt
  bin/images/aws/imagenes-ebs-csi-driver.txt
  bin/images/aws/imagenes-eks-distro.txt
  bin/images/azure/REGISTRY
  bin/images/azure/imagenes-capz.txt
  bin/images/azure/imagenes-cloud-controller.txt
  bin/images/azure/imagenes-cloud-node.txt
  bin/images/azure/imagenes-csi-azure.txt
  bin/images/azure/imagenes-csi-azuredisk-node.txt
  bin/images/azure/imagenes-csi-azurefile-node.txt
  bin/images/commons/REGISTRY
  bin/images/commons/imagenes-calico.txt
  bin/images/commons/imagenes-capi.txt
  bin/images/commons/imagenes-cert-manager.txt
  bin/images/commons/imagenes-cluster-autoscaler.txt
  bin/images/commons/imagenes-commons.txt
  bin/images/commons/imagenes-kind.txt
  bin/images/commons/imagenes-tigera.txt
  bin/images/gcp/REGISTRY
  bin/images/gcp/imagenes-capg.txt
  bin/images/gcp/imagenes-csi-gce.txt
  bin/images/gcp/imagenes-csi-node.txt
  bin/registry-push.sh
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-test, 0.4.0

#524 [CLOUD-254] [CLOUD-257] Added ClusterConfig docs
  stratio-docs/en/antora.yml
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/antora.yml
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
Labels: documentation, ok-to-merge, 0.4.0

#523 [CLOUD-253][Doc] Enable scale from zero for node groups
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#525 [CLOUD-255] Docs/cloud 255 support oci repos
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#528 [CLOUD-256] [Doc] Upgrade from 0.3.x to 0.4.0
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#530 [Docs] Add creation of LB controller for EKS
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan
