Repository Stratio/kind, pull requests merged in 2024-04, with the labels that each got.

#521 Add a PR template
  CONTRIBUTING.md
  pull_request_template.md
Labels: dont merge, wip, skip doUT, skip doGrypeScan

#535 👷FLOW-3090 - Add cluster template to CICD workflow
  Jenkinsfile
  bin/deploy.sh
  bin/package.sh
  docs/descriptor/keoscluster_v1beta1_template.yaml
Labels: need-cherry-pick-branch-0.17.0-0.4

#537 👷FLOW-3090 - Add cluster template to CICD workflow
  Jenkinsfile
  bin/deploy.sh
  bin/package.sh
  docs/descriptor/keoscluster_v1beta1_template.yaml
Labels: cherry-pick

#534 [CLOUD-205] Support k8s v1.28
  .gitignore
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-role.json
Labels: ok-to-merge, 0.5.0

#538 Prepare for next version: 0.6.0-SNAPSHOT
  VERSION
Labels: skip doUT, skip doGrypeScan, 0.5.0

#539 Fix VERSION
  VERSION
Labels: skip doUT, skip doGrypeScan
