Repository Stratio/kind, pull requests merged in 2024-06, with the labels that each got.

#550 Cherry/test gke 0.5
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, cherry-pick, 0.6.0

#557 [Update docs folder]
  docs/aws/Permissions/Azure.md
  docs/aws/accounts/new_accounts.md
Labels: documentation, 0.5.0, ok-to-review

#556 fixed scaled of ccm replicas in azure
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: bugfix, 0.5.0, ok-to-review

#558 [CLOUD-281] upgrade script 0.4.x to 0.5.0
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: 0.5.0, ok-to-review

#561 Stratio docs update
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.4.0, ok-to-review

#560 [DOC] Stratio docs Update
  docs/gcp/Permissions/gke_permissions_ref.md
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gke-permissions.list
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gke-permissions.list
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.5.0, ok-to-review

#563 [DOC] Modify version 1.26 to 1.28
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-merge, 0.5.0

#566 [DOC] Update docs folder information.
  docs/GCP/Permissions/gcp_permissions_ref.adoc
  docs/GCP/Permissions/todo.md
  docs/aws/Permissions/AWS/aws_permission_ref.adoc
  docs/aws/Permissions/AWS/aws_permission_ref.json
  docs/aws/Permissions/EKS/eks_permission_ref.json
  docs/azure/Permissions/Azure.md
  docs/cloud-provisioner/Versiones.md
  docs/gcp/Permissions/gcp_permissions_ref.md
  docs/gcp/Permissions/gke_permissions_ref.md
Labels: ok-to-merge, 0.5.0

#565 [DOC] Fix table view on pause version
  docs/cloud-provisioner/Versiones.md
Labels: ok-to-merge, 0.4.0

#564 [FIX] Fix the version of cloud provisioner
  CHANGELOG.md
  Makefile
  pkg/cmd/kind/version/version.go
Labels: bugfix, 0.5.0, cherry-pick, ok-to-review

#567 [Chore] Bump new version 0.17.0-0.5.1
  CHANGELOG.md
Labels: ok-to-merge, 0.5.1

#568 [Chore] Improve upgrade script
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, 0.5.1

#562 [DOC] Upgrade Documentation to Version 0.5.0
  stratio-docs/en/modules/operations-manual/assets/images/upgrade-cp.png
  stratio-docs/en/modules/operations-manual/assets/images/upgrade-w.png
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/assets/images/upgrade-cp.png
  stratio-docs/es/modules/operations-manual/assets/images/upgrade-w.png
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, 0.5.0, ok-to-review

#571 [Chore] Revert changes 0.5.1
  CHANGELOG.md
  pkg/cmd/kind/version/version.go
Labels: ok-to-review, 0.5.1

#569 [PLT-339] Clusterctl move management retries are not working
  CHANGELOG.md
  pkg/commons/utils.go
Labels: ok-to-merge, 0.5.1

#572 [Chore] Prepare release 0.5.1
  pkg/cmd/kind/version/version.go
Labels: ok-to-merge, 0.5.1

#575 [DOC] Fix AWS error reference on Azure and GCP files
  stratio-docs/en/modules/operations-manual/pages/image-builder/azure-image-builder.adoc
  stratio-docs/en/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
  stratio-docs/es/modules/operations-manual/pages/image-builder/azure-image-builder.adoc
  stratio-docs/es/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
Labels: documentation, 0.5.0, ok-to-review

#574 [Chore] Update versions in upgrade script
  CHANGELOG.md
  pkg/cmd/kind/version/version.go
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, 0.5.2
