Repository Stratio/kind, pull requests merged in 2024-09, with the labels that each got.

#587 [PLT-620] [Azure] Soportar imágenes públicas
  pkg/cluster/internal/validate/azure.go
Labels: cherry-pick, 0.5.3

#595 [PLT-563] Modify Dockerfile to add permissions on capg-manager role
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-merge, 0.6.0

#597 [FIX][0.6] Fix keoscluster-registries creation workload cluster
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bugfix, ok-to-merge, 0.6.0

#600 [DOC] Add compute.instanceGroupManagers.get to stratio-gke-permissions.list
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gke-permissions.list
Labels: ok-to-merge, 0.5.3

#590 docs fixes
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
Labels: documentation, 0.4.1

#591 docs fixes
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
Labels: documentation, 0.5.3

#592 docs fixes
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
Labels: documentation, 0.6.0
