Repository Stratio/kind, pull requests merged in 2024-11, with the labels that each got.

#627 [PLT-620] [Azure] Soportar imágenes públicas
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-merge, 0.6.0, need-cherry-pick-master

#628 Fixed GNP in GKE
  pkg/cluster/internal/create/actions/createworker/files/gcp/allow-egress-imds_gnetpol.yaml
Labels: bugfix, ok-to-test, skip doUT, skip doGrypeScan, 0.6.0, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, need-cherry-pick-master

#629 [PLT-1156] Add deny-all-egress-imds_gnetpol
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-review, 0.6.0
