Repository Stratio/kind, pull requests merged in 2024-07, with the labels that each got.

#536 [EKS] Add required permissions for AWS LB controller
  pkg/cluster/internal/create/actions/createworker/files/aws/public-ingress-nginx.yaml
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-merge, 0.6.0

#576 [CLOUD-45] Asegurar replicas de coredns en distintos nodos
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/createworker.go
Labels: ok-to-review, 0.6.0

#577 [Chore] Improve ExecuteCommand
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/utils.go
Labels: ok-to-review, 0.6.0

#545 [FIX][Upgrade] Support min_size to 0 in upgrade
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: 0.4.1, ok-to-review

#527 Fix panic when keos_version is not defined
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: bugfix, cherry-pick, 0.4.1, ok-to-review

#579 Delete keos.version and deploy_tigera_operator references
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/commons/cluster.go
Labels: cherry-pick, ok-to-review, 0.6.0

#581 Add keoscluster template for CICD
  docs/descriptor/keoscluster_v1beta1.yaml
  docs/descriptor/keoscluster_v1beta1_template.yaml
Labels: skip doUT, skip doGrypeScan
