Repository Stratio/kind, pull requests merged in 2024-01, with the labels that each got.

#359 [CLOUD-127] Refinar maxUnhealthy de MachineHealthCheck
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.5

#416 [FIX] fix pdb deployment
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.3.6, AT-gcp-smoke

#413 [CLOUD-147] Added s3 helm repository support
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, skip doUT, 0.4.0, AT-gcp-smoke

#410 [CLOUD-8] Feature/cloud 8 offline
  bin/images/aws/REGISTRY
  bin/images/aws/imagenes-aws.txt
  bin/images/aws/imagenes-capa.txt
  bin/images/aws/imagenes-ebs-csi-driver.txt
  bin/images/aws/imagenes-eks-distro.txt
  bin/images/azure/REGISTRY
  bin/images/azure/imagenes-capz.txt
  bin/images/azure/imagenes-cloud-controller.txt
  bin/images/azure/imagenes-cloud-node.txt
  bin/images/azure/imagenes-csi-azure.txt
  bin/images/azure/imagenes-csi-azuredisk-node.txt
  bin/images/azure/imagenes-csi-azurefile-node.txt
  bin/images/commons/REGISTRY
  bin/images/commons/imagenes-calico.txt
  bin/images/commons/imagenes-capi.txt
  bin/images/commons/imagenes-cert-manager.txt
  bin/images/commons/imagenes-cluster-autoscaler.txt
  bin/images/commons/imagenes-commons.txt
  bin/images/commons/imagenes-kind.txt
  bin/images/commons/imagenes-tigera.txt
  bin/images/gcp/REGISTRY
  bin/images/gcp/imagenes-capg.txt
  bin/images/gcp/imagenes-csi-gce.txt
  bin/images/gcp/imagenes-csi-node.txt
  bin/registry-push.sh
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/gcp-compute-persistent-disk-csi-driver.tmpl
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
  pkg/cluster/internal/validate/secrets.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/create/cluster/privateUtils.go
  pkg/cmd/kind/create/cluster/privatefiles/privateconfig.tmpl
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, skip doUT, 0.4.0

#415 Improve AWS in arch and install
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.3.0, skip doUT

#418 Utility to upload keos installer docker images
  scripts/README.md
  scripts/get-keos-docker-images-list.yml
  scripts/upload-images.py
Labels: skip doUT, 0.4.0

#419 [Azure] Fix azure cloud routes
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: ok-to-test, 0.3.7

#423 Update Lambda Info
  docs/aws/accounts/new_accounts.md
  scripts/ClustersWatch.py
  scripts/deleteUnusedEBS.py
  scripts/delete_oidc.py
Labels: skip doUT, 0.4.0

#382 Feature/add autoscaler annotations
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/gcp/gcp-compute-persistent-disk-csi-driver.yaml
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl
Labels: dont merge, ok-to-test, skip doUT

#427 Update EFS perm
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
Labels: skip doUT, 0.4.0

#429 Prepare release 0.3.7 fix
  CHANGELOG.md
Labels: skip doUT

#420 Feature/cloud 164 add new crd cluster config
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/commons/cluster.go
Labels: ok-to-merge, 0.4.0

#424 Cherry-pick: Fix broken links (#411)
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: skip doUT

#432 chore: update ExecuteCommand
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.3.8

#436 Rollback PR359 and PR419
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: skip doUT

#433 Disable Azure cloud routes
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: ok-to-test, 0.3.8

#417 [CLOUD-148] Soportar vpc_cidr sin especificar vpc_id ni subnets
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: ok-to-test, 0.4.0

#430 Fix CHANGELOG
  CHANGELOG.md
Labels: skip doUT, 0.3.7
