Repository Stratio/kind, pull requests merged in 2024-05, with the labels that each got.

#541 [FIX][Upgrade] Support OCI for helm URL in upgrade
  scripts/upgrade-provisioner.py
Labels: bugfix, cherry-pick, 0.4.1, ok-to-review

#542 [branch-0.2] Typo on architecture page and EN version updated
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
Labels: documentation, ok-to-merge

#446 [CLOUD-143] Test GKE updates
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/gcp/resourcequota.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/validate/gcp.go
Labels: feature, ok-to-merge, 0.5.0

#498 Update - installatio.adoc - Add Aws unmanaged uncoupled perms
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-test, skip doUT, skip doGrypeScan, 0.5.0

#546 [EKS] Add required permissions for AWS LB controller
  pkg/cluster/internal/create/actions/createworker/files/aws/public-ingress-nginx.yaml
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-merge, 0.5.0

#548 [CLOUD-143] Test GKE updates (#446)
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/gcp/resourcequota.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/validate/gcp.go
Labels: feature, 0.5.0, ok-to-review

#526 Fix panic when keos_version is not defined
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: bugfix, 0.5.0, ok-to-review

#551 [Cloud-278] Actualizar Permisos 0.5 en Azure (documentación [stratio-docs / docs])
  docs/azure/Permissions/Azure.md
  docs/azure/Permissions/Errros.md
  docs/azure/Permissions/azure_permission_ref.md
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-nodes-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-cp-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-nodes-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-nodes-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-cp-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-nodes-role.json
Labels: documentation, ok-to-test, 0.5.0

#549 [CLOUD-277] Reorganizar permisos de Azure
  docs/aws/Permissions/AWS/aws_Cloud_Formation.json
  docs/aws/Permissions/EKS/eks_Cloud_Formation.json
  docs/azure/Permissions/Azure.md
  docs/azure/Permissions/capz-role-control-plane.json
  docs/azure/Permissions/capz-role-node.json
  docs/azure/Permissions/capz-role-restricted.json
Labels: documentation, 0.5.0, ok-to-review

#543 [branch-0.3] EN and ES version aligned
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, ok-to-review

#552 branch-0.4] EN and ES version aligned
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, ok-to-merge, cherry-pick, ok-to-review

#554 [branch-0.5] EN and ES versions aligned (#552)
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, cherry-pick
