Repository Stratio/kind, pull requests merged in 2024-02, with the labels that each got.

#407 Fix cloud labels validation
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
Labels: ok-to-test, 0.4.0

#443 [CLOUD-191] Error en Documentación - Documentación 14.0 y 14.1: Cloud Provisioner
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: bug, documentation, ok-to-test, skip doUT, 0.3.8

#421 Disable azure cloud routes & fix azure csi drivers upgrade
  scripts/upgrade-provisioner_v0.3.py
Labels: ok-to-test, 0.3.8

#445 Sort aws temp policy permissions
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aws-temp-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-temp-policy.json
Labels: ok-to-merge, skip doUT, 0.3.8

#444 Add iam:CreatePolicyVersion to aws temp policy
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aws-temp-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-temp-policy.json
Labels: ok-to-merge, skip doUT, 0.4.0

#447 Upload images README info updated keos 1.0.5
  scripts/README.md
Labels: ok-to-merge, skip doUT, 0.3.8

#448 Enable Grype for Pull-requests
  Jenkinsfile
Labels: skip doUT, skip doGrypeScan

#451 Add iam permissions 0.3
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
Labels: ok-to-merge, 0.3.8

#456 Add keos 1.1 support
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
Labels: ok-to-test, 0.4.0, skip doGrypeScan

#453 [CLOUD-198] Actualizar versión de golang y alpine
  .go-version
  Jenkinsfile
  go.mod
  go.sum
Labels: ok-to-test, 0.4.0, skip doGrypeScan

#452 [FIX] Some fixes
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: bug, ok-to-test, 0.4.0, skip doGrypeScan

#459 Bump golang to 1.20
  .go-version
  Jenkinsfile
  go.mod
  go.sum
Labels: ok-to-test, 0.3.8, skip doGrypeScan

#357 [Azure] add validation of registry types
  pkg/cluster/internal/validate/azure.go
Labels: ok-to-test, 0.4.0, skip doGrypeScan

#431 required gcp permissions to validate instance types
  docs/gcp/Permissions/gcp_permission_ref.md
  docs/gcp/Permissions/gcp_permissions_ref.md
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
Labels: ok-to-test, 0.4.0, skip doGrypeScan

#455 Fix/offline docker login acr ecr gar
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cmd/kind/create/cluster/privateUtils.go
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#454 [CLOUD-193] Feature/cloud 193 support oci repositories for helm
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/keosinstaller.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/validate/secrets.go
  pkg/commons/cluster.go
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#460 Poc builder
  Dockerfile
  Jenkinsfile
  Makefile
Labels: dont merge, 0.4.0, AT-eks-smoke

#458 [CLOUD-210]Upgrade stratio-docs
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-merge, skip doUT, 0.4.0, skip doGrypeScan

#387 [CLOUD-137] Agregar posibilidad de escalado desde 0 en MachineDeployments y MachinePools
  CHANGELOG.md
  go.mod
  go.sum
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/autoscaler_rbac.tmpl
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/azure.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, 0.4.0, skip doGrypeScan

#462 Add grype tests
  Jenkinsfile
  Makefile
  pkg/cmd/kind/version/version.go
Labels: ok-to-test, 0.3.8

#463 Fix ci
  Jenkinsfile
Labels: ok-to-test, 0.4.0

#465 Fix grpc vulnerability
  go.mod
  go.sum
Labels: ok-to-test, AT-eks-smoke, 0.3.8

#358 [CLOUD-127] Refinar maxUnhealthy de MachineHealthCheck
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.4.0

#468 Fix/helm repo add
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-merge, 0.4.0

#470 update installation and quick-start-guide
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: skip doUT, 0.4.0, skip doGrypeScan

#471 Increase nmi rollout timeout
  pkg/cluster/internal/create/actions/createworker/provider.go
Labels: ok-to-test, 0.4.0

#469 Fix create_iam default behaviour (cherry-pick)
  pkg/commons/cluster.go
Labels: skip doUT, skip doGrypeScan

#474 [EOS-12292] KEOS permission requirement for ECR OCI helm repos
  docs/aws/Permissions/AWS/aws_permission.adoc
  docs/aws/Permissions/AWS/aws_permission_ref.json
  docs/aws/Permissions/EKS/eks_permission.adoc
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
Labels: documentation, skip doUT, 0.4.0, skip doGrypeScan

#475 Azure pre re-org perm
  docs/aws/Permissions/Azure.md
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#478 Move Azure.md to correct folder and permissions folder too
  docs/azure/Permissions/Azure.md
  docs/azure/Permissions/Errros.md
  docs/azure/Permissions/azure_permission_ref.md
  docs/azure/Permissions/capz-role-control-plane.json
  docs/azure/Permissions/capz-role-node.json
  docs/azure/Permissions/capz-role-restricted.json
Labels: ok-to-merge, skip doUT, 0.4.0, skip doGrypeScan

#467 [CLOUD-202] Feature/cloud 202 add maxunhealthy config to clusterconfig
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/common.go
  pkg/cluster/internal/validate/validate.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/commons/cluster.go
Labels: ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#466 [Feature ] Improve `vpc_cidr` logic
  docs/aws/Permissions/EKS/eks_Errros.md
  docs/aws/Permissions/EKS/eks_permission.adoc
  docs/aws/Permissions/EKS/eks_permission_ref.json
  pkg/cluster/internal/validate/aws.go
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
Labels: ok-to-merge, 0.4.0

#441 [CLOUD-169] [AWS] Refinar integracion de aws-loadbalancer-controller
  CHANGELOG.md
  DEPENDENCIES
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/files/aws/allow-egress-imds_gnetpol.yaml
  pkg/cluster/internal/create/actions/createworker/files/aws/public-ingress-nginx.yaml
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-merge, 0.4.0

#473 Update CHANGELOG for 0.4.0
  CHANGELOG.md
Labels: skip doUT, 0.4.0, skip doGrypeScan

#481 Fix errors
  docs/azure/Permissions/Azure.md
Labels: ok-to-merge, skip doUT, 0.4.0, skip doGrypeScan

#482 Fix failures
  docs/azure/Permissions/Azure.md
Labels: ok-to-merge, skip doUT, 0.4.0, skip doGrypeScan

#488 Update Azure role capz-role-restricted permissions
  docs/azure/Permissions/Errros.md
  docs/azure/Permissions/azure_permission_ref.md
  docs/azure/Permissions/capz-role-restricted.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-role.json
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#490 Update docs - scripts
  scripts/README.md
  scripts/delete_unused_ebs.py.py
  scripts/delete_unused_epis.py
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#492 Update eks permissions
  docs/aws/Permissions/EKS/eks_Errros.md
  docs/aws/Permissions/EKS/eks_permission.adoc
  docs/aws/Permissions/EKS/eks_permission_ref.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-eks-policy.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-eks-policy.json
Labels: documentation, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#494 [FIX] Remove print labels
  pkg/cluster/internal/validate/aws.go
Labels: bug, ok-to-test, skip doUT, 0.4.0, skip doGrypeScan

#499 [CLOUD-213] Hacer opcional el despliegue del aws-loadbalancer-controller en el ClusterConfig (default: no instalar)
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/overridevars.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/commons/cluster.go
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-test, 0.4.0

#503 Cherry pick execute command from 0.3
  pkg/commons/utils.go
Labels: bug, ok-to-test, 0.4.0, cherry-pick
