Repository Stratio/kind, pull requests merged in 2025-05, with the labels that each got.

#770 [PLT-2091][PLT-2098] Ensure flux NetworkPolicy requirements during cloud-provis…
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.6

#772 [PLT-2098] Improve kubernetes version checks during cloud-provisioner…
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-test, branch-0.7

#773 [branch-0.17.0-0.7] General errors fixed
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
Labels: documentation, need-cherry-pick-master, branch-0.7

#776 [PLT-2124] Bump cluster-autoscaler chart to 9.46.6 version
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-cluster-autoscaler.txt
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
Labels: dont merge, ok-to-test, need-cherry-pick-master, branch-0.7

#778 [PLT-2131] Improve workers checks during cloud-provisioner upgrade to avoid timeouts
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.5

#779 [PLT-2139] Fix cloud-provisioner upgrade issue when retrying upgrade …
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.6

#780 [PLT-2139] Fix cloud-provisioner upgrade issue when retrying upgrade …
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-test, branch-0.7

#777 [PLT-2099] [Upgrade] Problemas actualización Add-On CoreDNS en actualización de EKS
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/files/common/coredns_pdb.yaml
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-merge, branch-0.5

#781 [PLT-2132] Remove cri volumes management from upgrade
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.6

#784 [PLT-2116] Improve cluster-operator chart upgrade checks during cloud…
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.5

#786 [PLT-2132] Remove cri volumes management from upgrade
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.6

#788 [PLT-1496] Ensure CAPG provisioner version references are set to 1.6.…
  CHANGELOG.md
  DEPENDENCIES
  Jenkinsfile
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  pkg/commons/cluster.go
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: bugfix, ok-to-test, branch-0.7

#789 [PLT-2244] Deshabilitar CriVolume por defecto en instalación y en operación del cluster
  CHANGELOG.md
  pkg/cluster/internal/validate/aws.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, need-cherry-pick-master, branch-0.7

#790 [branch-0.17.0-0.7] Error in table
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
Labels: bugfix, documentation, branch-0.7

#791 [master] Error in table (#790)
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
Labels: bugfix, documentation, ok-to-merge, cherry-pick, master
