Repository Stratio/kind, pull requests merged in 2025-03, with the labels that each got.

#702 [PLT-1279] Bump cluster-operator references to 0.2.1 version
  CHANGELOG.md
  DEPENDENCIES
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: 0.4.1

#698 [PLT-1741] Bump cluster-operator references to 0.3.7 version. Update …
  DEPENDENCIES
  bin/images/commons/imagenes-cluster-operator.txt
  docs/cloud-provisioner/Versiones.md
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: 0.5.8, blocked

#699 [PLT-1741] Bump cluster-operator references to 0.4.2 version. Update …
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-cluster-operator.txt
  docs/cloud-provisioner/Versiones.md
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: blocked, 0.6.3

#703 [PLT-1423] Add pod disruption budget known issue documentation
  CHANGELOG.md
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, skip doGrypeScan, ok-to-review, 0.5.8

#689 [PLT-1621] Add kubernetes 1.32 support
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-cloud-controller-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-ebs-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-cloud-controller-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-ebs-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/31/azuredisk-azure-json.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/31/azuredisk-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/31/azurefile-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/31/cloud-provider-azure-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/32/azuredisk-azure-json.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/32/azuredisk-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/32/azurefile-csi-driver-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/azure/32/cloud-provider-azure-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/30/cert-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/cert-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/cluster-autoscaler-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2_helmrepository.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/tigera-operator-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/cert-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/cluster-autoscaler-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2_helmrepository.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/tigera-operator-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/31/coredns_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/31/coredns_deployment.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/31/gcp-cloud-controller-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/31/gcp-compute-persistent-disk-csi-driver.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/31/resourcequota.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/32/coredns_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/32/coredns_deployment.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/32/gcp-cloud-controller-manager-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/32/gcp-compute-persistent-disk-csi-driver.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/32/resourcequota.tmpl
  pkg/cluster/internal/validate/common.go
  pkg/cmd/kind/version/version_test.go
  scripts/templates/helmrelease_template.yaml
  scripts/templates/values/aws/cert-manager_default_values.tmpl
  scripts/templates/values/azure/cert-manager_default_values.tmpl
  scripts/upgrade-provisioner.py
Labels: wip, skip doUT, skip doGrypeScan, 0.7.0

#705 Chore/plt 1621 add new flag to upgrade
  scripts/templates/helmrelease_template.yaml
  scripts/upgrade-provisioner.py
Labels: skip doUT, skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.4

#713 [PLT-1887] Dynamic region describe
  CHANGELOG.md
  pkg/cluster/internal/validate/aws.go
Labels: ok-to-merge, 0.6.4

#714 [PLT-1887] Dynamic region describe
  CHANGELOG.md
  pkg/cluster/internal/validate/aws.go
Labels: skip doGrypeScan, 0.7.0

#717 [PLT-1887] Dynamic region describe
  CHANGELOG.md
  pkg/cluster/internal/validate/aws.go
Labels: skip doGrypeScan, 0.8.0

#721 [PLT-1849] Error 403 sts:AssumeRoleWithWebIdentity en ingress-nginx-controller
  pkg/cluster/internal/create/actions/createworker/templates/aws/30/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-load-balancer-controller-helm-values.tmpl
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: skip doGrypeScan, 0.8.0

#720 [PLT-1849] Error 403 sts:AssumeRoleWithWebIdentity en ingress-nginx-controller
  pkg/cluster/internal/create/actions/createworker/templates/aws/30/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-load-balancer-controller-helm-values.tmpl
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-test, skip doGrypeScan, 0.7.0

#719 [PLT-1849] Error 403 sts:AssumeRoleWithWebIdentity en ingress-nginx-controller
  pkg/cluster/internal/create/actions/createworker/templates/aws/28/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/29/aws-load-balancer-controller-helm-values.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/aws/30/aws-load-balancer-controller-helm-values.tmpl
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-test, 0.6.4

#724 [DOC] [EKS] Update aws-load-balancer documentation
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, skip doGrypeScan, 0.8.0

#723 [DOC] [EKS] Update aws-load-balancer documentation
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, skip doGrypeScan, 0.7.0

#722 [DOC] [EKS] Update aws-load-balancer documentation
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.6.4

#708 [PLT-1652] Allow skipping kubernetes intermediate version during upgrade
  CHANGELOG.md
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-merge, 0.5.8

#709 [PLT-1652] Allow skipping kubernetes intermediate version during upgrade
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  scripts/requirements.txt
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: documentation, ok-to-merge, 0.6.4

#718 [PLT-1652] Allow skipping kubernetes intermediate version during upgrade
  CHANGELOG.md
  scripts/requirements.txt
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: documentation, ok-to-merge, skip doGrypeScan, need-cherry-pick-master, 0.7.0

#727 [PLT-1652] Allow skipping kubernetes intermediate version during upgr…
  scripts/requirements.txt
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: documentation, ok-to-merge, skip doGrypeScan, cherry-pick, 0.8.0

#731 [PLT-1849] Fix aws-load-balancer-controller annotation
  CHANGELOG.md
Labels: 0.6.4

#732 [PLT-1849] Fix aws-load-balancer-controller annotation
  CHANGELOG.md
Labels: 0.7.0

#733 [PLT-1849] Fix aws-load-balancer-controller annotation
  CHANGELOG.md
Labels: 0.8.0

#707 [PLT-1823] Improve Clouds credentials management documentation
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/operations-manual/pages/credentials.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/credentials.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-merge, master

#736 [PLT-1823] Improve Clouds credentials management documentation (#707)
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/operations-manual/pages/credentials.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/credentials.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: ok-to-merge, cherry-pick, 0.7.0

#737 [PLT-1823] Improve Clouds credentials management documentation (#707)
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/operations-manual/pages/credentials.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/credentials.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: ok-to-merge, cherry-pick, 0.6.4

#741 [PLT-1922] Rename reference to aws-load-balancer-controller
  CHANGELOG.md
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
Labels: need-cherry-pick-master, 0.6.5, need-cherry-pick-branch-0.17.0-0.7
