Repository Stratio/kind, pull requests merged in 2025-08, with the labels that each got.

#811 [PLT-1761][Clouds] Actualizar documentación 0.6.x
  stratio-docs/en/modules/ROOT/assets/attachments/nodes-cluster-api-provider-aws-sigs-k8s-io.json
  stratio-docs/en/modules/ROOT/assets/attachments/nodes-trust-relationship.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/en/modules/ROOT/assets/images/icons/azure.svg
  stratio-docs/en/modules/ROOT/assets/images/icons/eks.svg
  stratio-docs/en/modules/ROOT/assets/images/icons/gke.svg
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/introduction.adoc
  stratio-docs/en/modules/ROOT/pages/what-is-new.adoc
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/en/modules/operations-manual/pages/credentials.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/nodes-cluster-api-provider-aws-sigs-k8s-io.json
  stratio-docs/es/modules/ROOT/assets/attachments/nodes-trust-relationship.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/es/modules/ROOT/assets/images/icons/azure.svg
  stratio-docs/es/modules/ROOT/assets/images/icons/eks.svg
  stratio-docs/es/modules/ROOT/assets/images/icons/gke.svg
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/introduction.adoc
  stratio-docs/es/modules/ROOT/pages/what-is-new.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/modules/operations-manual/pages/credentials.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: ok-to-review, need-cherry-pick-master, branch-0.6, need-cherry-pick-branch-0.17.0-0.7

#825 [PLT-2656] Bump Tigera Operator version to v3.30.2
  CHANGELOG.md
  DEPENDENCIES
  docs/images/commons/imagenes-calico.txt
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/templates/common/32/tigera-operator-helm-values.tmpl
  stratio-docs/en/modules/ROOT/pages/what-is-new.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: ok-to-test, master

#829 [PLT-2723] Bump aws-ebs-csi-driver, coredns, kube-proxy and vpc-cni addons versions
  CHANGELOG.md
  DEPENDENCIES
Labels: ok-to-merge, master
