Repository Stratio/kind, pull requests merged in 2025-06, with the labels that each got.

#793 [master] Typos in tables (#792)
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
Labels: documentation, cherry-pick, master

#782 [PLT-2143][PLT-2244] Bump cluster-operator to 0.4.3 version to upgrade issues
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-cluster-operator.txt
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: ok-to-merge, branch-0.6, upgrade

#794 [PLT-2226] [cloud-provisioner] Usar repo privado por defecto
  CHANGELOG.md
  pkg/commons/cluster.go
  stratio-docs/en/modules/ROOT/pages/what-is-new.adoc
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/modules/ROOT/pages/what-is-new.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
Labels: documentation, ok-to-test, branch-0.7

#756 [PLT-1762] [EKS] Soportar instalaciones con Assume Role
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/secrets.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/create/cluster/privateUtils.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
Labels: ok-to-merge, branch-0.7

#796 [PLT-2259] Revisar la creación del kubeconfig para EKS durante la instalación con cloud-provisioner
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/commons/kubeconfig.go
Labels: ok-to-merge, branch-0.7

#785 [PLT-2108] Configurar Assume role (STS) de forma manual
  CHANGELOG.md
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: dont merge, ok-to-test, skip doGrypeScan, need-cherry-pick-master, branch-0.7

#802 [PLT-2335] No levanta docker keos-installer con parámetro role_arn:'false' en secrets.yaml
  pkg/cluster/internal/validate/aws.go
  pkg/cluster/internal/validate/utils.go
  pkg/commons/cluster.go
  pkg/commons/utils.go
Labels: ok-to-test, need-cherry-pick-master, branch-0.7

#804 [PLT-2379] Fix namespace reference
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: ok-to-merge, need-cherry-pick-master, branch-0.7

#808 [PLT-2389] Fix image reference during cluster creation
  CHANGELOG.md
  pkg/cluster/internal/providers/docker/images.go
Labels: bugfix, ok-to-test, branch-0.7

#810 [Update] Assume role documentation
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: ok-to-review, need-cherry-pick-master, branch-0.7
