Repository Stratio/kind, pull requests merged in 2025-02, with the labels that each got.

#676 Fix/upgrade some fixes
  pkg/cluster/internal/create/actions/createworker/provider.go
  scripts/templates/values/aws/cluster-operator_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_override_values.tmpl
  scripts/templates/values/azure/cluster-operator_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_override_values.tmpl
  scripts/upgrade-provisioner.py
Labels: bugfix, skip doUT, skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.2

#677 Adding changelog
  CHANGELOG.md
Labels: skip doUT, skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.2

#678 [branch-017.0-0.4] Eliminación de referencias a GCP/CKE
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/introduction.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/en/modules/operations-manual/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/en/modules/operations-manual/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/en/modules/operations-manual/assets/images/deps-gce.png
  stratio-docs/en/modules/operations-manual/assets/images/google-service-account.png
  stratio-docs/en/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/introduction.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/operations-manual/assets/images/build-gce-ubuntu-2204-part1.png
  stratio-docs/es/modules/operations-manual/assets/images/build-gce-ubuntu-2204-part2.png
  stratio-docs/es/modules/operations-manual/assets/images/deps-gce.png
  stratio-docs/es/modules/operations-manual/assets/images/google-service-account.png
  stratio-docs/es/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-review

#681 Chore/fixing upgrade script 05 06
  scripts/templates/values/aws/cluster-operator_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_override_values.tmpl
  scripts/templates/values/azure/cluster-operator_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_override_values.tmpl
  scripts/upgrade-provisioner.py
Labels: ok-to-test, skip doGrypeScan, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.2

#679 [PLT-1656] Fix cluster-operator upgrade cloud-provisioner upgrade whe…
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: bugfix, ok-to-merge, 0.5.8

#680 [PLT-1654] Fix AWS ClusterRole patch during cloud-provisioner upgrade
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: bugfix, ok-to-merge, 0.5.8

#675 [PLT-1628] Fix coredns, cluster-api-gcp and kube-rbac-proxy image registry and repository references
  CHANGELOG.md
  DEPENDENCIES
  bin/images/aws/imagenes-capa.txt
  bin/images/commons/imagenes-capi.txt
  bin/images/gcp/imagenes-coredns.txt
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/gcp/28/coredns_deployment.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/29/coredns_deployment.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/gcp/30/coredns_deployment.tmpl
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: bugfix, ok-to-merge, 0.6.2

#684 [branch-0.17.0-0.4] Errores en tablas
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
Labels: bugfix, documentation

#661 [PLT-1393] Bump Tigera Operator version to v3.29.1
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-calico.txt
  bin/images/commons/tigera-operator.txt
  docs/cloud-provisioner/Versiones.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/gcp.go
  pkg/cluster/internal/create/actions/createworker/templates/common/30/tigera-operator-helm-values.tmpl
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: ok-to-merge, skip doGrypeScan, 0.7.0

#687 Feature/plt 1496 add support extended channel
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, need-cherry-pick-master, 0.6.2

#688 Feature/plt 1496 add support extended channel (#687)
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: skip doGrypeScan, 0.7.0

#686 [PLT-1628] Fix capz images registry and repository references. Replace cloud-provider-azure …
  DEPENDENCIES
  bin/images/azure/imagenes-capz.txt
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
Labels: ok-to-merge, 0.6.2

#692 [PLT-1317] Remove non-suported AKS, managed AWS and managed GCP references
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: documentation, ok-to-merge, 0.7.0

#694 [branch-0.17.0-0.6] antora.yml version update to 0.6
  stratio-docs/en/antora.yml
  stratio-docs/es/antora.yml
Labels: bugfix, documentation, ok-to-merge, ok-to-review

#685 [PLT-1682] Improve kindest/node and stratio-capi-image management
  DEPENDENCIES
  Jenkinsfile
  bin/images/commons/imagenes-kind.txt
  docs/gcp/GKE Bastion.md
  pkg/apis/config/defaults/image.go
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/providers/docker/images.go
  pkg/cluster/internal/providers/docker/provider.go
  pkg/cluster/internal/providers/docker/provision.go
  pkg/cluster/internal/providers/podman/provider.go
  pkg/cluster/internal/providers/provider.go
  pkg/cluster/provider.go
  pkg/cmd/kind/create/cluster/createcluster.go
  pkg/cmd/kind/root.go
  pkg/cmd/kind/version/version.go
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: skip doGrypeScan, ok-to-review, 0.7.0, improvement

#695 [PLT-1716] [EKS] Desplegar utilizando únicamente el parámetro pods_cir en networks falla
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
Labels: need-cherry-pick-master, 0.6.2

#696 Update cluster-api-gcp-controller version references
  DEPENDENCIES
  bin/images/gcp/imagenes-capg.txt
Labels: need-cherry-pick-master, 0.6.2

#700 Update cluster-api-gcp-controller version references
  DEPENDENCIES
  bin/images/gcp/imagenes-capg.txt
Labels: skip doGrypeScan

#701 [PLT-1741] Bump cluster-operator references to 0.5.0 version. Update …
  CHANGELOG.md
  DEPENDENCIES
  bin/images/commons/imagenes-cluster-operator.txt
  docs/cloud-provisioner/Versiones.md
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
Labels: ok-to-merge, skip doGrypeScan, cherry-pick, 0.7.0
