Repository Stratio/kind, pull requests merged in 2025-01, with the labels that each got.

#651 [Doc] Update Bastion documentation
  .gitignore
  docs/gcp/GKE Bastion.md
  docs/gcp/Permissions/gcp_permissions_ref.adoc
  docs/gcp/Permissions/todo.md
Labels: 0.5.8

#652 [Doc] Update Bastion documentation
  .gitignore
  docs/gcp/GKE Bastion.md
Labels: 0.6.1

#653 [Doc] Update Bastion documentation
  .gitignore
  docs/gcp/GKE Bastion.md
Labels: 0.7.0

#654 [Doc] fix Columns
  stratio-docs/en/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-merge, 0.5.8

#655 [Doc] fix Columns
  stratio-docs/en/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.6.1

#656 [Doc] fix Columns
  stratio-docs/en/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-merge, 0.7.0

#642 [PLT-1330] CMEK, SA & CIDRs
  CHANGELOG.md
  pkg/cluster/internal/validate/gcp.go
  pkg/commons/cluster.go
Labels: ok-to-test, ok-to-merge

#648 [PLT-1309] Update docker images requirements documentation. Include stratio-capi-image to cicd flow
  DEPENDENCIES
  Jenkinsfile
  bin/images/aws/imagenes-aws-cloud-controller-manager.txt
  bin/images/aws/imagenes-aws-load-balancer-controller.txt
  bin/images/aws/imagenes-ebs-csi-driver.txt
  bin/images/aws/imagenes-eks-distro.txt
  bin/images/azure/imagenes-azuredisk-csi-driver.txt
  bin/images/azure/imagenes-azurefile-csi-driver.txt
  bin/images/azure/imagenes-capz.txt
  bin/images/azure/imagenes-cloud-controller.txt
  bin/images/azure/imagenes-cloud-node.txt
  bin/images/azure/imagenes-cloud-provider-azure.txt
  bin/images/azure/imagenes-csi-azure.txt
  bin/images/azure/imagenes-csi-azuredisk-node.txt
  bin/images/azure/imagenes-csi-azurefile-node.txt
  bin/images/commons/imagenes-calico.txt
  bin/images/commons/imagenes-cert-manager.txt
  bin/images/commons/imagenes-cluster-autoscaler.txt
  bin/images/commons/imagenes-cluster-operator.txt
  bin/images/commons/imagenes-commons.txt
  bin/images/commons/imagenes-flux.txt
  bin/images/commons/imagenes-kind.txt
  bin/images/commons/imagenes-tigera.txt
  bin/images/commons/tigera-operator.txt
  bin/images/gcp/imagenes-capg.txt
  bin/images/gcp/imagenes-csi-node.txt
  bin/images/gcp/imagenes-gcp-cloud-controller-manager.txt
  bin/images/gcp/imagenes-gcp-compute-persistent-disk-csi-driver.txt
  docs/gcp/GKE Bastion.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/commons/cluster.go
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: documentation, ok-to-merge, skip doGrypeScan, 0.6.1

#649 [PLT-1309] Update docker images requirements documentation
  DEPENDENCIES
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: documentation, ok-to-merge, 0.5.8

#657 [PLT-1332] [GKE] Validaciones parámetros GKE
  pkg/cluster/internal/create/create.go
  pkg/cluster/internal/delete/delete.go
  pkg/cluster/internal/validate/gcp.go
Labels: ok-to-merge, 0.6.1

#650 Updated doc for 0.5.X
  DEPENDENCIES
  bin/images/aws/imagenes-ebs-csi-driver.txt
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-cp-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-nodes-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/introduction.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-cp-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-nodes-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aks-role.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-aws-unmanaged-policy.json
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/introduction.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-aks-images.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Labels: documentation, ok-to-review, need-cherry-pick-master, 0.5.8, need-cherry-pick-branch-0.17.0-0.6

#660 [PLT-1332] [GKE] Fix and improve validations
  pkg/cluster/internal/validate/gcp.go
Labels: bugfix, wip, 0.6.1

#659 [PLT-1396] Imagenes bastionadas
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, 0.5.8

#665 [branch-0.17.0-0.5] Several fixes on the installation page
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: documentation, ok-to-review, need-cherry-pick-master, need-cherry-pick-branch-0.17.0-0.6, improvement

#643 Added script upgrade from 0.5 to 0.6.
  .gitignore
  Jenkinsfile
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  scripts/files/aws/globalnetpol_allow.yaml
  scripts/files/flux-values.yaml
  scripts/requirements.txt
  scripts/templates/helmrelease_template.yaml
  scripts/templates/helmrepo-test.yaml
  scripts/templates/helmrepository_template.yaml
  scripts/templates/values/aws/aws-cloud-controller-manager_default_values.tmpl
  scripts/templates/values/aws/cert-manager_default_values.tmpl
  scripts/templates/values/aws/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_override_values.tmpl
  scripts/templates/values/aws/flux2_default_values.tmpl
  scripts/templates/values/aws/flux_default_values.tmpl
  scripts/templates/values/aws/tigera-operator_default_values.tmpl
  scripts/templates/values/azure/azuredisk-csi-driver_default_values.tmpl
  scripts/templates/values/azure/azurefile-csi-driver_default_values.tmpl
  scripts/templates/values/azure/cert-manager_default_values.tmpl
  scripts/templates/values/azure/cloud-provider-azure_default_values.tmpl
  scripts/templates/values/azure/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_override_values.tmpl
  scripts/templates/values/azure/flux2_default_values.tmpl
  scripts/templates/values/azure/flux_default_values.tmpl
  scripts/templates/values/azure/tigera-operator_default_values.tmpl
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/ROOT/nav.adoc
  stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/ROOT/nav.adoc
  stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: documentation, ok-to-merge, 0.6.1

#670 Updated Jenkinsfile
  Jenkinsfile
Labels: bugfix, skip doUT, skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.1

#671 Updated CAPG version
  DEPENDENCIES
  Jenkinsfile
  bin/images/gcp/imagenes-capg.txt
  pkg/cluster/internal/providers/docker/stratio/Dockerfile
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  pkg/commons/cluster.go
  stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
Labels: skip deadExternalLinks, skip doEmptyLines, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks, 0.6.1

#672 [PLT-1165] Documentar GKE 0.6.x
  stratio-docs/en/modules/ROOT/pages/architecture.adoc
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
  stratio-docs/es/modules/ROOT/pages/architecture.adoc
  stratio-docs/es/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Labels: documentation, need-cherry-pick-master, 0.6.1
