Repository Stratio/kind, pull requests merged in 2025-04, with the labels that each got.

#744 [PLT-1910] Instalar en Azure con infra creada
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-acr.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/en/modules/ROOT/assets/attachments/stratio-azure-role-rg.json
  stratio-docs/en/modules/ROOT/pages/installation.adoc
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-acr.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/es/modules/ROOT/assets/attachments/stratio-azure-role-rg.json
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: ok-to-review, need-cherry-pick-master, need-cherry-pick-branch-0.17.0-0.6, 0.5.9, need-cherry-pick-branch-0.17.0-0.7

#740 [PLT-1917][PLT-1968][PLT-1971][PLT-1957][PLT-1956][PLT-1958] Improve upgrade flow
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/28/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/28/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/29/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/29/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/30/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/30/flux2_helmrelease.tmpl
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  scripts/files/flux-values.yaml
  scripts/templates/helmrelease_template.yaml
  scripts/templates/helmrepo-test.yaml
  scripts/templates/helmrepository_template.yaml
  scripts/templates/values/aws/aws-cloud-controller-manager_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_override_values.tmpl
  scripts/templates/values/aws/flux_default_values.tmpl
  scripts/templates/values/azure/azuredisk-csi-driver_default_values.tmpl
  scripts/templates/values/azure/azurefile-csi-driver_default_values.tmpl
  scripts/templates/values/azure/cert-manager_default_values.tmpl
  scripts/templates/values/azure/cloud-provider-azure_default_values.tmpl
  scripts/templates/values/azure/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_override_values.tmpl
  scripts/templates/values/azure/flux2_default_values.tmpl
  scripts/templates/values/azure/flux_default_values.tmpl
  scripts/templates/values/azure/tigera-operator_default_values.tmpl
  scripts/templates/values/cert-manager_default_values.tmpl
  scripts/templates/values/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/flux_default_values.tmpl
  scripts/templates/values/tigera-operator_default_values.tmpl
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: ok-to-merge, 0.6.5

#752 [PLT-1917][PLT-1968][PLT-1971][PLT-1957][PLT-1956][PLT-1958] Improve …
  CHANGELOG.md
  pkg/cluster/internal/create/actions/createworker/aws.go
  pkg/cluster/internal/create/actions/createworker/azure.go
  pkg/cluster/internal/create/actions/createworker/createworker.go
  pkg/cluster/internal/create/actions/createworker/provider.go
  pkg/cluster/internal/create/actions/createworker/templates/common/30/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/30/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/31/flux2_helmrelease.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2-helm-chart-values_configmap.tmpl
  pkg/cluster/internal/create/actions/createworker/templates/common/32/flux2_helmrelease.tmpl
  pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
  scripts/templates/helmrelease_template.yaml
  scripts/templates/helmrepo-test.yaml
  scripts/templates/helmrepository_template.yaml
  scripts/templates/values/aws/aws-cloud-controller-manager_default_values.tmpl
  scripts/templates/values/aws/cert-manager_default_values.tmpl
  scripts/templates/values/aws/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_default_values.tmpl
  scripts/templates/values/aws/cluster-operator_override_values.tmpl
  scripts/templates/values/aws/flux2_default_values.tmpl
  scripts/templates/values/aws/flux_default_values.tmpl
  scripts/templates/values/aws/tigera-operator_default_values.tmpl
  scripts/templates/values/azure/azuredisk-csi-driver_default_values.tmpl
  scripts/templates/values/azure/azurefile-csi-driver_default_values.tmpl
  scripts/templates/values/azure/cert-manager_default_values.tmpl
  scripts/templates/values/azure/cloud-provider-azure_default_values.tmpl
  scripts/templates/values/azure/cluster-autoscaler_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_default_values.tmpl
  scripts/templates/values/azure/cluster-operator_override_values.tmpl
  scripts/templates/values/azure/flux2_default_values.tmpl
  scripts/templates/values/azure/flux_default_values.tmpl
  scripts/templates/values/azure/tigera-operator_default_values.tmpl
  scripts/upgrade-provisioner.py
  stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/en/modules/operations-manual/pages/installation.adoc
  stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
  stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
  stratio-docs/es/modules/operations-manual/pages/installation.adoc
  stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
  stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
Labels: ok-to-merge, 0.7.0

#755 [PLT-2032] Fix default Helm repository management type during cloud-p…
  CHANGELOG.md
  scripts/upgrade-provisioner.py
Labels: ok-to-merge, branch-0.5

#760 [branch-0.17.0-0.5] DOC - little fixes
  stratio-docs/es/modules/ROOT/pages/installation.adoc
Labels: bugfix, documentation, ok-to-merge, ok-to-review, need-cherry-pick-master, need-cherry-pick-branch-0.17.0-0.6, need-cherry-pick-branch-0.17.0-0.7, branch-0.5

#766 [DOC] Align to 0.7 installation adoc [es/en] (#765)
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-acr.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-acr.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-role-rg.json
Labels: documentation, cherry-pick, branch-0.6

#767 [DOC] Align to 0.7 installation adoc [es/en] (#765)
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-acr.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/en/modules/operations-manual/assets/attachments/stratio-azure-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-acr.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-cp-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-nodes-role-rg.json
  stratio-docs/es/modules/operations-manual/assets/attachments/stratio-azure-role-rg.json
Labels: documentation, cherry-pick, branch-0.7

#769 [PLT-2052] Fix Azure charts versions references
  pkg/cluster/internal/create/actions/createworker/azure.go
Labels: ok-to-merge, branch-0.6
